name: flikka
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  loading_animation_widget: ^1.2.0+4
  google_fonts: ^6.1.0
  get: ^4.6.5

  image_picker: ^1.0.2
  dotted_border: ^2.0.0+3
  file_picker: ^6.1.1
  open_file: ^3.0.1
  webview_flutter: ^4.4.1
  flutter_downloader: ^1.11.4
  intl: ^0.18.0

#  card_swiper: ^3.0.1
  flutter_card_swiper: ^6.0.0
  comment_box: ^0.0.18
  share_plus: ^7.1.0
  url_launcher: ^6.1.12
  flutter_share: ^2.0.0
  geolocator: ^10.1.0
  fluttertoast: ^8.0.9
  geocoding: ^2.1.0
  google_maps_flutter: ^2.5.0
  permission_handler: ^11.0.0
  flutter_screenutil: ^5.5.3+2
#  device_preview: ^1.1.0
  pull_to_refresh: ^2.0.0
  textfield_search: ^0.10.0
  flutter_advanced_switch: ^3.0.1
  path_provider: ^2.1.0
#  dropdown_button2: ^1.9.2
  geocode: ^1.0.2
  flutter_svg: ^2.0.7
  dropdown_button2: ^2.3.8
  fl_chart: ^0.65.0
#  geocoder2: any
  table_calendar_null_safe: any
  omni_datetime_picker: ^1.0.8
  http: ^1.1.0
  new_pinput: ^1.0.1
#  pinput: ^3.0.1
  shared_preferences: ^2.2.1
  lottie: ^2.6.0
  clipboard: ^0.1.3
  flutter_image_compress: ^2.0.4
  image_cropper: ^5.0.0
  cached_network_image: ^3.3.0
  percent_indicator: ^4.2.3
  html: ^0.15.4
  flutter_widget_from_html_core: ^0.14.7
  country_picker: ^2.0.22
  intl_phone_field: ^3.2.0
  video_player: ^2.8.1
  chewie: ^1.7.1
  video_compress: ^3.1.2
  flutter_rating_bar: ^4.0.1
  firebase_core: any
  cloud_firestore: ^4.9.0
  firebase_storage: ^11.2.6
  firebase_database: ^10.2.5
  firebase_messaging: any
  google_sign_in: ^6.2.1
  video_trimmer: ^2.1.0
#  audioplayers: ^5.2.1
  audio_waveforms: ^1.0.4
#  kplayer: ^0.4.2
  flutter_local_notifications: ^16.2.0
  fast_contacts: ^3.1.2



#  table_calendar: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

